services:
  postgres-produits:
    image: postgres:15-alpine
    container_name: postgres-produits
    environment:
      POSTGRES_DB: produits_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 071013
    ports:
      - "5433:5432"
    volumes:
      - postgres_produits_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - examtp2026-network

  postgres-avis:
    image: postgres:15-alpine
    container_name: postgres-avis
    environment:
      POSTGRES_DB: avis_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 071013
    ports:
      - "5434:5432"
    volumes:
      - postgres_avis_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - examtp2026-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - examtp2026-network

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - examtp2026-network
    environment:
      EUREKA_SERVER_ENABLE_SELF_PRESERVATION: "false"

  produits-service:
    build: ./produits-service
    container_name: produits-service
    ports:
      - "8091:8091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-produits:5432/produits_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 071013
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      postgres-produits:
        condition: service_healthy
      redis:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - examtp2026-network

  avis-service:
    build: ./avis-service
    container_name: avis-service
    ports:
      - "8092:8092"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-avis:5432/avis_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 071013
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      postgres-avis:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - examtp2026-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8090:8090"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - examtp2026-network

networks:
  examtp2026-network:
    driver: bridge

volumes:
  postgres_produits_data:
  postgres_avis_data: