version: '3.8'

services:

  # ── Bases de données ──────────────────────────
  postgres-produits:
    image: postgres:16
    container_name: postgres-produits
    environment:
      POSTGRES_DB: produits_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_produits_data:/var/lib/postgresql/data

  postgres-avis:
    image: postgres:16
    container_name: postgres-avis
    environment:
      POSTGRES_DB: avis_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_avis_data:/var/lib/postgresql/data

  # ── Redis ─────────────────────────────────────
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  # ── Eureka Server ─────────────────────────────
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── Produits Service ──────────────────────────
  produits-service:
    build: ./produits-service
    container_name: produits-service
    ports:
      - "8091:8091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-produits:5432/produits_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres-produits
      - redis
      - eureka-server

  # ── Avis Service ──────────────────────────────
  avis-service:
    build: ./avis-service
    container_name: avis-service
    ports:
      - "8092:8092"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-avis:5432/avis_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres-avis
      - eureka-server

  # ── API Gateway ───────────────────────────────
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8090:8090"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

volumes:
  postgres_produits_data:
  postgres_avis_data: