server.port=8090
spring.application.name=api-gateway

# Route vers produits-service
spring.cloud.gateway.routes[0].id=produits-service
spring.cloud.gateway.routes[0].uri=lb://produits-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/produits/**

# Route vers produits-service pour categories
spring.cloud.gateway.routes[1].id=categories-service
spring.cloud.gateway.routes[1].uri=lb://produits-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/categories/**

# Route vers avis-service
spring.cloud.gateway.routes[2].id=avis-service
spring.cloud.gateway.routes[2].uri=lb://avis-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/avis/**

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Activer la découverte via Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true